version: '3.4'

services:
  api:
    build:
      context: .
      target: production
    ports:
      - 3334:3000
    environment:
      JWT_SECRET: LosChimiChimitos
      PORT: 3000
      API_SALUDO: http://localhost:5555/hola/
      MONGO_URI_HEADER: mongodb+srv://signas13:wyENLJGUgCyjb4BV@
      MONGO_CLUSTER: cluster0.a1cig.mongodb.net/test?retryWrites=true&w=majority
      USER_TEST_USERNAME: test
      USER_TEST_PASSWORD: 1111111111
