version: '3.4'

services:
  api:
    build:
      context: .
      target: development
    restart: always
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3334:3000
    command: npm run dev
